version: '3.9'

services:
  lanars-postgres:
    image: postgres:alpine
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lanars
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  